name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - run: pytest --junitxml=report.xml || true

      - uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: report.xml

      - name: Slack Notification
        env:
          WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          STATUS=$(grep -o 'failures="[0-9]*"' report.xml)
          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"Test Run Completed: $STATUS\"}" \
          $WEBHOOK
